### ISSUE TITLE
View and ViewModel c-tors are called on navigation to existing page

### ISSUE THREAD

**Issue by bobbybonifacia** [exrin/Exrin#12]
When the page is already in the navigation stack and we navigate to it with newInstance=false parameter, the c-tor of view and viewModel is still called.
It looks like these new instances are not used, because the "old" page version is still shown.

**Comment by adamped** [comment]
@bobbybonifacia - Fixed and tested in Exrin 1.2.2. Please re-open if you continue to experience the issue.
