### ISSUE TITLE
VisualState-ModelState two-way binding crashes the app

### ISSUE THREAD

**Issue by bobbybonifacia** [exrin/Exrin#14]
When I set the Two-way binding attribute to an int or decimal property in VisualState (have the same property in ModelState), app crashes on navigation to the page. However, when the property type is a reference one (custom class), no crash.
How do I use it:
in VisualState class
`[Binding(BindingType.TwoWay)]
public int SomeValue
{
	get { return Get<int>(); }
	set { Set(value); }
}`

in ModelState class
`public int SomeValue
{
	get { return Get<int>(); }
	set { Set(value); }
}`

I use Exrin 1.2.4. Tested on iOS and Android.

**Comment by adamped** [comment]
@bobbybonifacia @CavalomIV - fixed in Exrin 1.2.5. Was a StackOverflow issue, because the test for equality was assuming reference types, not value. Two other bug fixes, also included in this release.
