### ISSUE TITLE
OnAppearing event in ViewModel doesn't fire when view re-displayed

### ISSUE THREAD

**Issue by johndownskloud** [exrin/Exrin#15]
I have a ViewModel that contains some logic that I'd like to run whenever the view is displayed. This would include when the user explicitly navigates to the page, and also if the user backgrounds the app and then re-foregrounds it.

The OnAppearing event only fires when the view is shown for the first time. If I background the app and then re-open it, the OnAppearing event does not re-fire.

Is this a bug in Exrin's OnAppearing implementation? Or would it be possible to add a new event that gets fired whenever the view is re-opened?

(Also, if this does get fixed, it'd be great if it was an async event!)

**Comment by adamped** [comment]
@johndownskloud - the OnAppearing event is just relayed from the page, hence if its not running, then the event is not being fired by Xamarin Forms. You won't get the OnAppearing event to fire when it comes back in from the background. What you need to look at is the App.xaml.cs and the OnResume event that is called there.
