### ISSUE TITLE
Select detail stack

### ISSUE THREAD

**Issue by omniium** [exrin/Exrin#17]
I used a MasterDetailContainer and I can to set default DetailStack when creating class. How can I change DetailStack from ViewModel or Operation?

**Comment by adamped** [comment]
You just need to Navigate to it. Just reference it by Stack and ViewKey. Either using NavigationService or returning the Result in an operation.

**Comment by omniium** [comment]
I mean: have master page with navigation (search, settings etc.) and detail page with main stack. I want to click a button on master page and on detail to open needs stack. For example, I click "Settings" and Detail = SettingsStack, click "Search" - Detail = SearchStack.
All stacks I declered here (like for tabbed):
public MasterDetailContainer(MasterStack masterStack, MainStack stackMain, SearchStack stackSearch, SettingsStack stackSettings)

**Comment by adamped** [comment]
Currently Exrin can't switch a stack, in a specific container location. Though its something I want to add in, but we just need to think of how it can be implemented. The only thing I can think of at the moment is to provide a key/name to each location, inside a Container. Then add another option to the navigation result/service of switching a container.

**Comment by adamped** [comment]
I have just implemented this feature in 1.3.0-beta1: https://www.nuget.org/packages/Exrin/1.3.0-beta1

I wrote a quick article about it here: https://xamarinhelp.com/container-region-stack-navigation-exrin/

Give it a try and let me know if you have any issues. Feel free to Reopen if there are problems with it, or submit a new issue.
