### ISSUE TITLE
Initial navigation to a non-root page doesn't work after Android back button

### ISSUE THREAD

**Issue by bobbybonifacia** [exrin/Exrin#18]
On app start we load not the root page of the stack, but another page in this stack: e.g. stack has pages A and B, A is root, on app start the user sees the B page.
However, when the app is resumed after Android back button pressed, the page A is loaded instead of page B.
Is it possible to always have the navigation to non-root page?

**Comment by adamped** [comment]
When a user presses the back in Android at the last page, it actually kills the app. If you want to suspend the app instead, in your MainActivity.cs you can do this.

```
public override void OnBackPressed()
{
    MoveTaskToBack(true);
}
```

This backgrounds the app, instead of killing it.

**Comment by bobbybonifacia** [comment]
@adamped by default the back button behavior is handled in the way, that the MainActivity is finished, but app is still running. After starting the MainActivity again (without killing the app) we experience navigation to the root page.

**Comment by adamped** [comment]
If you start the MainActivity again, the LoadApplication runs, and so does all the Xamarin Forms and Exrin initialization. Its starting the activity from scratch again. Hence you need to store its state, then manually get it back there, or don't kill the activity.

There is no current way that Exrin can store its current state, because it doesn't know anything about Android, its just loaded in memory.

**Comment by bobbybonifacia** [comment]
So when the MainActivity is started and the Xamarin Forms, Exrin are initialized from scratch, why the navigation to page B is not performed (page A is shown instead)?
In App.cs c-tor we always navigate with these stack options:  new StackOptions { StackChoice = Stacks.Main, ViewKey = Main.B.ToString() }.

**Comment by adamped** [comment]
Can we please run through this again to make sure I understand.

You load up your app and it starts
-> Page B

Then you close your app by pressing the back button.

Then when you start the app again it shows
-> Page A

**Comment by bobbybonifacia** [comment]
@adamped yes

**Comment by adamped** [comment]
I cant seem to replicate this issue. Is there any chance you could provide a small reproduction of the issue.

**Comment by bobbybonifacia** [comment]
@adamped yes, you can use this sample: https://github.com/bobbybonifacia/ExrinTestApp
How to reproduce: open app (second page is visible), press back button (first page visible), press back button (app "closes"), open app from "recent apps" (first page is shown instead of second page).

**Comment by adamped** [comment]
My mistake, when Android shuts down the activity is gone but everything is still in memory.

Hence when you load the app again, it just starts it from where it left off.

Did you want it to completely die, when the activity is killed?

Hence if you want to kill the process as well, when you press the back button you can do

android.os.Process.killProcess(android.os.Process.myPid());

or you could manually start disposing of everything.

**Comment by adamped** [comment]
Adding to that, it's mostly kept all in memory in the IoC Container. Hence if you add an additional method in the Injection Proxy, to just make the container null when the Activity is closed, it should wipe all state from the app, also if you set the MainPage in App.xaml.cs to a blank ContentPage.

**Comment by bobbybonifacia** [comment]
@adamped using
android.os.Process.killProcess(android.os.Process.myPid());
solves the problem for us, thank you!
