### ISSUE TITLE
Modelling ListView's ViewCell navigation to a Page and back

### ISSUE THREAD

**Issue by JimSEOW** [exrin/Exrin#19]
I am trying to figure out Exrin approach to model Container(Region), Stack etc in a variety of cases: MasterDetail, TabbedPage, CarouselPage. 

=> Please let me know if the diagram is consistent with your concept, where it is wrong?
=> Question: For a SingleContainer where (region = container) it contains a stack. Instead of hosting navigationPage with many pages, how about hosting a ListView with many ViewCells with each ViewCell (tapping) leading to navigation to other page: Is the diagram consistent with your concept?

=> Suggestion:
Is it possible to navigate from other page to a specific ViewCell of a ListView?
Is it possible to navigate SPECIFICALLY to a particular ViewCell of a ListView? For example, when the navigation is triggered to a particular ViewCell (e.g. ViewCell5), The ListView will adjust the scrolling so that ViewCell5 is position top of the screen. Can this be done? How to model that in Exrin?

![2017-06-18_11-01-23](https://user-images.githubusercontent.com/8244633/27259557-c145f70e-5415-11e7-9e5f-21de48663150.png)

**Comment by adamped** [comment]
Yes, this is mostly correct. The ListView's though, are inside ContentPage's, not directly in a Navigation Page.

Hence if you want to navigate from a ViewCell to another page, or directly to a ViewCell in a page, you just need to navigate to that page, then in that ViewModel of the Page, use the ScrollTo method to bring the exact ViewCell into view.

**Comment by JimSEOW** [comment]
@adamped  Congratulation of Exrin 2.0 beta. Clearly Logical!
