### ISSUE TITLE
NoHistory Bug: navigating to page pops two views instead of one

### ISSUE THREAD

**Issue by wecaBah** [exrin/Exrin#2]
We have three pages in the stack a, b, c. The b page has the property NoHistory. If we navigate to the c page from b, b should be popped. But instead a and b are popped.

**Comment by adamped** [comment]
hi @wecaBah. I have replicated the issue. It seems to be an issue in the Xamarin Forms framework and I am currently trying to track it down.

**Comment by adamped** [comment]
@wecaBah - I have found the error, it was based in Exrin after all. I have released Exrin 1.0.4-beta2, which includes the fix. Please let me know and reopen this if you continue to experience the issue.
