### ISSUE TITLE
Constructor injection for pages

### ISSUE THREAD

**Issue by DelcoigneYves** [exrin/Exrin#22]
Hi Adam

I'm wondering why there is no support for constructor injection for pages. Is this by design?

If not, this could be an easy improvement in the ViewService, by using the same code that is used for construction of the viewmodel (first checking for a constructor with parameters instead of immediately throwing an exception).

**Comment by adamped** [comment]
My main philosophy is to keep the XAML clean, and have no code-behind. However I imagine there might be valid reasons for doing so. What did you need to inject into a view?

**Comment by DelcoigneYves** [comment]
Currently I'm refactoring a project to use Exrin, and there are some helper classes that are injected in the page. I realize that what is currently in the code behind can certainly be put in the viewmodel, so my case isn't really a valid one, but as you said, someday I might have a valid reason to need it :)
