### ISSUE TITLE
ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by bobbybonifacia** [exrin/Exrin#23]
In our exrin-based app we have a page with ViewModel and VisualState. In VisualState.Init() method we set the property value, which has TwoWay binding with Entry text on the page. Sometimes the app crashes with System.ArgumentException and message "An item with the same key has already been added. Key: AccountName".
Below is the stacktrace we receive via our crash reporting framework:
"StackTrace": [
      {
        "LineNumber": 0,
        "ClassName": "System.Collections.Generic.Dictionary"2[TKey,TValue]",
        "FileName": "<05f1faf1b5a5495492b5915bd7997bab>",
        "MethodName": "TryInsert(TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior)",
        "Raw": "at System.Collections.Generic.Dictionary"2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) [0x000bb] in <05f1faf1b5a5495492b5915bd7997bab>:0"
      },
      {
        "LineNumber": 0,
        "ClassName": "System.Collections.Generic.Dictionary"2[TKey,TValue]",
        "FileName": "<05f1faf1b5a5495492b5915bd7997bab>",
        "MethodName": "Add(TKey key, TValue value)",
        "Raw": "at System.Collections.Generic.Dictionary"2[TKey,TValue].Add (TKey key, TValue value) [0x00000] in <05f1faf1b5a5495492b5915bd7997bab>:0"
      },
      {
        "LineNumber": 0,
        "ClassName": "Exrin.Framework.BindableModel",
        "FileName": "<9cad413ef20541cba580af846615376e>",
        "MethodName": "Set(System.Object value, System.String propertyName)",
        "Raw": "at Exrin.Framework.BindableModel.Set (System.Object value, System.String propertyName) [0x00039] in <9cad413ef20541cba580af846615376e>:0"
      },
      {
        "LineNumber": 0,
        "ClassName": "BusinessLogic.ViewModels.Login.LoginVisualState",
        "FileName": "<39af0bcb93174e72986e600c97507149>",
        "MethodName": "set_AccountName(System.String value)",
        "Raw": "at BusinessLogic.ViewModels.Login.LoginVisualState.set_AccountName (System.String value) [0x00000] in <39af0bcb93174e72986e600c97507149>:0"
      },
      {
        "Raw": "at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)"
      },
      {
        "LineNumber": 0,
        "ClassName": "System.Reflection.MonoMethod",
        "FileName": "<05f1faf1b5a5495492b5915bd7997bab>",
        "MethodName": "Invoke(System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture)",
        "Raw": "at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00032] in <05f1faf1b5a5495492b5915bd7997bab>:0"
      }
I tried to debug the navigation to the page. It looks like the VisualState.Init() method is called in background thread, but the BindingContext for the page is assigned in UI thread. So, there is a small probability that the Set() method can be called from different threads for the same property on page initialization.
Unfortunately, I wasn't able to reproduce this exception for sure and make a test app for this. Should we initialize properties only in UI thread in VisualState.Init() to avoid such problems?

We also sometimes get the same exception for the ViewModel.GetCommand method: on the ViewModel we have a command which can be triggered from UI and background thread. Should we also restrict the command execution to UI thread only?

**Comment by adamped** [comment]
@bobbybonifacia - this would actually be caused by something trying to set the initial value of a property at the same time in different threads. Which thread it's on wouldn't have made any difference. I have just pushed out 2.0.3, which contains a bug fix.
