### ISSUE TITLE
KeyNotFoundException - App crash

### ISSUE THREAD

**Issue by cavaIV** [exrin/Exrin#24]
Hello!

We receive an error in Exrin.
The error occurs in [ViewModelExecute.cs in line 142 ](https://github.com/exrin/Exrin/blob/f4e8b39f4113d07663cf8dc00e6aaa8f601da2ba/Exrin/Exrin.Framework/Framework/ViewModelExecute.cs#L142)

It seems like it happens when 2 operations (from the same ViewModel) are executed in two different threads the dictionary key (sender) gets removed in the first thread while the second thread reaches line 142 and the KeyNotFoundException occurs.

**Stack trace**

System.Collections.Generic.Dictionary2[TKey,TValue].get_Item(TKey key) in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.10.0.36/src/mono/mcs/class/referencesource/mscorlib/system/collections/generic/dictionary.cs:183
Exrin.Framework.Process.ViewModelExecute() in ..\1.3.1\Exrin\Exrin.Framework\ViewModelExecute.cs:142
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.10.0.36/src/mono/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:151
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.10.0.36/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.10.0.36/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(System.Threading.Tasks.Task task) in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.10.0.36/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128
System.Runtime.CompilerServices.TaskAwaiter.GetResult() in /Library/Frameworks/Xamarin.iOS.framework/Versions/10.10.0.36/src/mono/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:113
 
Exrin.Framework.Process+<>c__DisplayClass12_0+<<ViewModelExecute>b__0>d.MoveNext() in ..\1.3.1\Exrin\Exrin.Framework\ViewModelExecute.cs:107

**Comment by adamped** [comment]
Fixed the issue with Exrin 2.0.5: https://www.nuget.org/packages/Exrin/2.0.5
