### ISSUE TITLE
IndexOutOfRangeException - ViewModelExecute

### ISSUE THREAD

**Issue by cavaIV** [exrin/Exrin#25]
Hey!

We receive an exception in the ViewModelExecute.
This also looks like a threading related issue but I'm not sure if it's fixed with https://github.com/exrin/Exrin/issues/24
Could you please have a look?

Stack trace
Message: Index was outside the bounds of the array.
  System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert(TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) in <136edfc8e644410eb152bce382121c61#d487899ec0a2d69231706767c4c2a347>:0
  System.Collections.Generic.Dictionary`2[TKey,TValue].Add(TKey key, TValue value) in <136edfc8e644410eb152bce382121c61#d487899ec0a2d69231706767c4c2a347>:0
 
  Exrin.Framework.Process.ViewModelExecute() in <9cad413ef20541cba580af846615376e#d487899ec0a2d69231706767c4c2a347>:0
  System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task task) in <136edfc8e644410eb152bce382121c61#d487899ec0a2d69231706767c4c2a347>:0
  System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task task) in <136edfc8e644410eb152bce382121c61#d487899ec0a2d69231706767c4c2a347>:0
  System.Runtime.CompilerServices.TaskAwaiter.GetResult() in <136edfc8e644410eb152bce382121c61#d487899ec0a2d69231706767c4c2a347>:0
 
  Exrin.Framework.Process+<>c__DisplayClass12_0+<<ViewModelExecute>b__0>d.MoveNext() in <9cad413ef20541cba580af846615376e#d487899ec0a2d69231706767c4c2a347>:0

**Comment by adamped** [comment]
I have fixed this by using ConcurrentDictionaries. Didn't realize Dictionaries weren't thread safe, and if you try to add/remove at the same time as a similar operation, you can get this issue. Switching to ConcurrentDictionaries stops the issues. This is now available in https://www.nuget.org/packages/Exrin/2.0.6

**Comment by cavaIV** [comment]
Thanks for your fast reply!
I can't see the change - have you pushed it to GitHub?

**Comment by adamped** [comment]
I just pushed it to GitHub now, but the nuget package went out 11 hrs ago.
