### ISSUE TITLE
OnBackNavigated for current page is triggered when another page is silent pop.

### ISSUE THREAD

**Issue by bobbybonifacia** [exrin/Exrin#28]
In order to dispose the view model and visual state (as it is done in Exrin sample app) on page silent pop, I use the following in Navigation proxy:

```
public Task SilentPopAsync(int indexFromTop)
{
  var page = _page.Navigation.NavigationStack[_page.Navigation.NavigationStack.Count - indexFromTop - 1];
  _page.Navigation.RemovePage(page);
  OnPopped?.Invoke(this, new ViewNavigationArgs() { Parameter = null, CurrentView = _page.CurrentPage as IView, PoppedView = page as IView });
  return Task.FromResult(true);
}
```

It does trigger the Disposing() on ViewModel of the page, which is popped, but I also got OnBackNavigated called for the currently visible page view model. Is that an expected behavior?

Example: Navigation stack A -> B -> C. On page C silent pop page B. BViewModel.Disposing() is called, but also CViewModel.OnBackNavigated() is called.

**Comment by adamped** [comment]
@bobbybonifacia It's not. I found the issue, introduced because I now made the SilentPop call OnPopped.

Fix in Exrin 2.0.8: https://www.nuget.org/packages/Exrin/2.0.8
