### ISSUE TITLE
Custom Navigation renderer animated bool is always false

### ISSUE THREAD

**Issue by maftrapp** [exrin/Exrin#3]
In my custom renderer I am using the OnPushAsync to create a custom animation when pages is changed, in my exrin project the animated bool is always coming as false, (in my non-exrin project the animated bool always comes as true). Below is 

```
public class AnimationNavigationRenderer : NavigationRenderer
{
   protected override Task<bool> OnPushAsync(Page page, bool animated)
   {
       if (animated || true) 
      {
           // rendering code
       }
    }
}
```

In my exrin NavigationProxy my PuschAsync method is below

```
		public async Task PushAsync(object page)
		{
			var xamarinPage = page as Page;

			if (xamarinPage == null)
			{
				throw new Exception($"{nameof(PushAsync)} can not push a non Xamarin Page");
			}
			await navigationPage.PushAsync(xamarinPage, true);
		}
```

In xamarin the OnPushAsync should always be coming as true (when not specifically set to false) [from xamarin](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs)
```
public Task<bool> PushPageAsync(Page page, bool animated = true)
{
			return OnPushAsync(page, animated);
}
```

The only place where I can see the PushPageAsync animated bool being set to false is line 214 [from xamarin](https://github.com/xamarin/Xamarin.Forms/blob/master/Xamarin.Forms.Platform.iOS/Renderers/NavigationRenderer.cs)  called on viewdidLoad().
```
// If there is already stuff on the stack we need to push it
((INavigationPageController)navPage).StackCopy.Reverse().ForEach(async p => await PushPageAsync(p, false));
```

The Question is then is it possible that exrin is somehow changing the animated bool in the background?

**Comment by adamped** [comment]
@maftrapp - Exrin doesn't know anything about Xamarin Forms. The NavigationProxy is the only point that has a reference to PushAsync. If you set animated to true on the PushAsync, or leave it out altogether, Exrin has no part of what happens after that and therefore it should be true.

I am thinking something else is happening here, but im not sure what.

Just to clarify, you are break pointing in your custom renderer and NavigationProxy, and can see its set to true in the Proxy, then when it comes to your custom renderer the animated property is false?

**Comment by maftrapp** [comment]
ok that's what I was thinking, but for now I will just ignore the animated bool and look at it later.

Thanks for the help.
