### ISSUE TITLE
Exrin firing OnNavigated method in ViewModel when app initialised and view not presented yet

### ISSUE THREAD

**Issue by michaeldimoudis** [exrin/Exrin#6]
Hi, I have a basic Xamarin Forms app using Exrin. Thhe first view is just a simple auth page, once logged in it goes to a tabbed page. The Views, and consequently ViewModels in the tabbed page, are getting initialised and their `OnNavigated` methods are been fired on app start up, even when user is not logged in so the auth page is showing and tabbed page hasn't been navigated to yet.

Then when logged in, and the tabbed page is brought in to view, the `OnNavigated` methods for those view models in the tabbed page get re-fired. I'm not sure if I am doing something wrong, or it's an Exrin bug? For completeness, even the `VisualState` `Init()` method for those View Models also gets fired on app start up.

My bootstrapper is stock standard as per the template:
```
    Bootstrapper.GetInstance(platform)
            .Init()
            .Get<INavigationService>()
            .Navigate(new StackOptions()
            {
                StackChoice = Stacks.Authentication
            });
```
With an Authentication Container and Main Container (which inherits from `ITabbedContainer`)

The `TabbedView` proxy example is from the Tesla sample app, including a lot of the code I'm playing around with. Any help would be greatly appreciated. Thanks.

**Comment by adamped** [comment]
@michaeldimoudis - in the TabbedProxy that will be in your code, if you took it from the sample, shows a call to StartNavigation, for each page, when its built. If you comment out that line, it will hopefully stop doing the multiple OnNavigated.

**Comment by michaeldimoudis** [comment]
@adamped thanks for the reply. I did that, however when I navigate to the TabbedPage stack, I get:
```NavigationPage must have a root Page before being used. Either call PushAsync with a valid Page, or pass a Page to the constructor before usage.```

Good news is, the views aren't getting initialised, bad news is this error. Any other ideas?

**Comment by adamped** [comment]
@michaeldimoudis - Try out https://www.nuget.org/packages/Exrin/1.1.0-beta1

Still remove the StartNavigation your TabbedViewContainer. This will now start the Stacks, when they are navigated to, if they aren't already started.

**Comment by michaeldimoudis** [comment]
Thanks. It works for iOS :)
However getting this error on Android `Sequence contains no elements`.

I tried adding back StartNavigation in my TabbedViewContainer and I wasn't getting that crash, but obviously the view models were getting initialised on app start up in that case.

Even tried `child.StartNavigation(child.NavigationStartKey, false);` with no success.

**Comment by adamped** [comment]
ok, almost there :) Will look further into it just after work today, see if I can reproduce the crash. Do you have a stacktrace for it, instead of just the error message?

**Comment by michaeldimoudis** [comment]
Yep nearly there :) No problem take your time, no rush.
Unfortunately I can't dig further in to the error message, not sure if the debugger can see what's in the exrin dll's...

**Comment by adamped** [comment]
I might have to try it out with your package, as I just tried on Android with the Tesla example and it all worked fine. I can't reproduce the Sequence contains no elements error. Do you experience it still on the Tesla example and if so what device or emulator / version are you running on?

**Comment by michaeldimoudis** [comment]
Managed to get more stack trace info
```System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.Last[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00079] in /Users/builder/data/lanes/4009/f3074d2c/source/mono/mcs/class/referencesource/System.Core/System/Linq/Enumerable.cs:1009
  at Xamarin.Forms.Platform.Android.AppCompat.NavigationPageRenderer.OnAttachedToWindow () [0x00011] in C:\BuildAgent3\work\ca3766cfc22354a1\Xamarin.Forms.Platform.Android\AppCompat\NavigationPageRenderer.cs:191
  at Android.Views.View.n_OnAttachedToWindow (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in /Users/builder/data/lanes/4009/9578cdcd/source/monodroid/src/Mono.Android/platforms/android-25/src/generated/Android.Views.View.cs:14163
  at at (wrapper dynamic-method) System.Object:c97c7e8c-2815-4c20-a48e-8d5e33adc0e6 (intptr,intptr)
```

**Comment by michaeldimoudis** [comment]
Oh my goodness, I'm so sorry. When I updated all nuget packages, it missed the Android project for some reason and I didn't notice it. :embarrassing: I just updated Android to Exrin 1.1.0-beta1 and it's all working. Thanks for fixing this 😃

**Comment by adamped** [comment]
It happens :)
