### ISSUE TITLE
Pushing a container to a Modal?

### ISSUE THREAD

**Issue by michaeldimoudis** [exrin/Exrin#7]
Hi

Any tips on how to do this? I can't find any examples, or a best approach on how to push a container as modal.

Looking at the Exrin code, might have to change `BaseStack.cs`, create a `NavigationModal` `ResultType`, etc...?

Any other ideas?

**Comment by adamped** [comment]
I'm just moving the convo back here as now its moved more into a feature request :) As discussed there are no modals, you would use another stack.

However that leaves out the animations. We could add modal support, however I still think it goes against the intention of never having them. I am interested to see if we might be able to get animations in stack changes.

**Comment by michaeldimoudis** [comment]
Nice :) if it's possible to specify if a stack change can animate, simply push up and then push down, that would be awesome.

**Comment by adamped** [comment]
Ok, will have to work on how to implement this but it is possible. If you copy and paste the FormsAppDelegate.cs from the Xamarin source code then update this:

void UpdateMainPage()
        {
            if (_application.MainPage == null)
                return;

            var platformRenderer = (PlatformRenderer)_window.RootViewController;

            if (platformRenderer != null)
                ((IDisposable)platformRenderer.Platform).Dispose();
            if (_window.RootViewController == null)
                _window.RootViewController = _application.MainPage.CreateViewController();
            else
                UIView.Transition(_window.RootViewController.View, 1, UIViewAnimationOptions.TransitionFlipFromBottom, () => { _window.RootViewController = _application.MainPage.CreateViewController(); }, () => { });

        }

It will provide a transition effect, when changing the main page. Now I just need to work out how to do it in Android, then how to provide it. Will most likely have to see if I can get a change committed to the XF Team.

**Comment by adamped** [comment]
In Platform.cs in Android, we can get the animation happening by replacing the AddChild function with the one below.
        void AddChild(Page page, bool layout = false)
        {
            if (Android.Platform.GetRenderer(page) != null)
                return;

            Android.Platform.SetPageContext(page, _context);
            IVisualElementRenderer renderView = Android.Platform.CreateRenderer(page);
            Android.Platform.SetRenderer(page, renderView);

            if (layout)
                LayoutRootPage((FormsAppCompatActivity)_context, page, _renderer.Width, _renderer.Height);

            renderView.ViewGroup.StartAnimation(global::Android.Views.Animations.AnimationUtils.LoadAnimation(_context, global::Android.Resource.Animation.SlideInLeft));

            _renderer.AddView(renderView.ViewGroup);
        }

However this approach, shows the existing page disappear, then the new page animates it. That might be a problem. Now onto UWP.

**Comment by adamped** [comment]
In UWP we add in this to the SetCurrent method in Platform.cs, just before the Children.Add line.

          if (_container.ChildrenTransitions == null)
            {
                _container.ChildrenTransitions = new TransitionCollection();
                _container.ChildrenTransitions.Add(new EntranceThemeTransition());

            }

Now I need to figure out how to best implement this for an API proposal in XF.

**Comment by michaeldimoudis** [comment]
@adamped nice one! I tried the iOS version but couldn't proceed as copying FormsAppDelegate did not build due to protected methods etc. Good luck with the API proposal for XF :)

**Comment by vasylmosiiuk** [comment]
maybe better to use Popup pages implementation like this one ([https://github.com/rotorgames/Rg.Plugins.Popup] and add new one ModalNavigationArgs:INavigationArgs

**Comment by adamped** [comment]
A workaround on how to show a Modal, has been given at:
http://stackoverflow.com/questions/42660205/xamarin-forms-exrin-framework-pushing-a-container-as-a-modal/42660251#42660251

A request for XF to accept an API change to provide animations on MainPage changes has also been submitted.
https://forums.xamarin.com/discussion/90558/mainpage-animated-transitions
