### ISSUE TITLE
.xproj load failed

### ISSUE THREAD

**Issue by EltonGarcia** [exrin/Exrin#8]
Hi Adam, at first I have to say that your project seems terrific, thank you for this. Unfortunately, I still couldn't take a look at all because I am facing a problem to open it. The .xproj projects into Core folder and the Exrin.Inspector.xproj are failing to load and I can't figure out the reason why.

I am using VS 2015 update 3 with Xamarin support and I have the .Net Core installed and I am able to create and run both Xamarin projects and .Net Core projects.

Did you have any idea of what might be missing in my environment?

Thanks for everything.

**Comment by adamped** [comment]
Can you create your own new .xproj project (.net core), or does that fail to load as well?

**Comment by EltonGarcia** [comment]
Well, when I create a new .Net Core project the extension is .csproj because the .xproj has already been depreciated. 

http://www.talkingdotnet.com/bye-bye-project-json-xproj-welcome-back-csproj/

**Comment by adamped** [comment]
Its only deprecated in VS 2017, unless the new .NET Core Tools that
recently dropped convert it. If you are using VS 2017, it will popup asking
to migrate to csproj. If you are on VS 2015, it should open the xproj. I'll
download the latest .NET Core tools for VS 2015 and see what happens.

**Comment by adamped** [comment]
I loaded the new .NET Core Tools. I can still successfully open the project. Are you sure you are using VS2015 and not VS2017.

Also I will be upgrading this project to csproj soon.

**Comment by adamped** [comment]
The Exrin project has now been upgraded to VS 2017 and uses csproj.
