### ISSUE TITLE
OutOfMemoryException during build when referencing Exrin 1.1.2

### ISSUE THREAD

**Issue by johndownskloud** [exrin/Exrin#9]
I have an app that currently references an older version of Exrin. I've just tried to upgrade the package reference to 1.1.2, and now when I build my Android app I get this error:

```
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1534,2): warning : Exception of type 'System.OutOfMemoryException' was thrown.
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1534,2): warning :    at Microsoft.Cci.Pdb.MsfDirectory..ctor(PdbReader reader, PdbFileHeader head, BitAccess bits)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1534,2): warning :    at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, BitAccess bits, Boolean readAllStrings)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1534,2): warning :    at Microsoft.Cci.Pdb.PdbFile.LoadFunctions(Stream read, Boolean readAllStrings)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1534,2): warning :    at Pdb2Mdb.Converter.Convert(String filename)
2>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1534,2): warning :    at Xamarin.Android.Tasks.ConvertDebuggingFiles.Execute()
```

This repeats four times in the build log. It happens when I build locally from VS2015, and when I build from VSTS using the Android build task. It also happens whether I use the x86 or x64 JDK and MSBuild.

I've checked the older versions in NuGet, and it worked fine right up to (and including) Exrin 1.1.1. It's only 1.1.2 that has this issue.

**Comment by adamped** [comment]
Hmm, Exrin 1.1.2 was the first time I built it in VS 2017, maybe this could be the issue.

I did a search around and found this: https://developercommunity.visualstudio.com/content/problem/16160/cannot-debug-code-from-referenced-net-standard-lib.html

and this:
https://forums.xamarin.com/discussion/74067/forms-droid-build-causes-system-outofmemoryexception

Seems to be an issue with .NET Standard libraries with the MS Build tools. Unfortunately nothing I can do on that side, but would be interested to see if there is anything I can do on my project side to help.

Try the workarounds in the above and let me know.

**Comment by johndownskloud** [comment]
Thanks. I've checked the suggested workarounds, and unfortunately neither works:

 * The `<DebugType>full</DebugType>` was already set.
 * The Java Max Heap Size setting was already set to 1G.

**Comment by adamped** [comment]
I have just tried this out and see these errors as well, but they don't stop the build or deploy. I assume it still all works for you?

I will keep this issue open until the source of these issues are found.

**Comment by johndownskloud** [comment]
Thanks. It's true the warnings don't stop the build, but I'm a little uncomfortable with it, since there may be unknown side effects further down the line. So I don't plan on upgrading to the latest Exrin package until this is resolved. Thanks for your help - please let me know if I give any more info to help to resolve this.

**Comment by adamped** [comment]
@johndownskloud - I have just tried this again, with the latest version of Exrin, with the latest updates to Visual Studio. I no longer receive this error. If you confirm all is working on your end, I will close the issue.

**Comment by johndownskloud** [comment]
Thanks @adamped - I just tested and it looks like this is resolved by the latest VS2017 update.
